### ISSUE TITLE
practica de proposiciones 

### ISSUE THREAD

**Issue by Anais-droid** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Anais-droid#1]
[INSTITUTO.TECNOLOGICO.NACIONAL.DE.MEIXCO1 (2).pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Anais-droid/files/13289727/INSTITUTO.TECNOLOGICO.NACIONAL.DE.MEIXCO1.2.pdf)

**Comment by LuisAlexisMorales** [comment]
Portada:25
Procedimiento:20
Figuras:22
Resultados:17
Total:84. calificación final: 19.4
Por equipo de: Luis Alexis Morales José

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
